```{r}
.libPaths(c(.libPaths(), "/home/lchanem1/rlibs/4.0.2/gcc/9.3.0"))
library(ggplot2)
library(reshape)
library(tidyr)
library(dplyr)
```

```{r}
data <- data.frame(
  Category = c("Zihe_1", "Iisa_3", "Uilk_3", "Xojn_3", "Qehq_3", "Eipl_1", "Letw_1", "Sojd_3", "Poih_4", "Joxm_1"),
  High = c(0.98, 0.99, 0.99, 0.99, 0.99, 0.98, 0.99, 0.99, 0.98, 0.99),
  Low = c(0.93, 0.97, 0.98, 0.97, 0.97, 0.97, 0.97, 0.98, 0.96, 0.98),
  Medium = c(0.96, 0.98, 0.98, 0.96, 0.98, 0.97, 0.98, 0.97, 0.93, 0.97),
  Total = c(0.79, 0.88, 0.95, 0.93, 0.93, 0.93, 0.94, 0.96, 0.91, 0.95)
)

melted_data <- melt(data, id.vars = "Category")

primary_colors <- c("navy", "lavender", "coral", "grey")

plot <- ggplot(melted_data, aes(x = Category, y = value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Sample", y = "Pearson Correlation", fill = "Coverage Category") +
  scale_fill_manual(values = primary_colors) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.text.y = element_text(size = 12),
        axis.title.y = element_text(size = 14),
        plot.margin = unit(c(0.2, 0.5, 0.2, 0.5), "cm"))
plot + coord_cartesian(ylim = c(0.75, 1))
```


```{r}
data <- data.frame(
  Sample = c('Zihe_1', 'Iisa_3', 'Uilk_3', 'Xojn_3', 'Sojd_3', 'Poih_4', 'Eipl_1', 'Letw_1', 'Qehq_3', 'Joxm_1'),
  `10 kbp flank exclude` = c(0.88, 0.90, 0.92, 0.90, 0.94, 0.89, 0.90, 0.91, 0.90, 0.93),
  `100 kbp flank exclude` = c(0.84, 0.87, 0.88, 0.86, 0.92, 0.86, 0.87, 0.88, 0.87, 0.90),
  `500 kbp flank exclude` = c(0.80, 0.83, 0.85, 0.79, 0.89, 0.83, 0.83, 0.84, 0.81, 0.84),
  `1 mbp flank exclude` = c(0.76, 0.79, 0.83, 0.75, 0.87, 0.81, 0.81, 0.80, 0.76, 0.81)
)
data_melted <- melt(data, id.vars = "Sample", variable.name = "Flank_Exclude", value.name = "Correlation")
ggplot(data_melted, aes(x = factor(Flank_Exclude), y = Correlation, group = Sample, color = Sample)) +
  geom_line() +
  geom_point() +
  scale_x_discrete(labels = c("10 kbp", "100 kbp", "500 kbp", "1 mbp")) +
  labs(x = "Distance from nearest gene on count matrix", y = "Pearson Correlation") +
  ylim(0.70, 1) +
  theme_minimal()
```

Visualization for correlations of SNPs within a said distance from nearest gene on count matrix:
```{r}
data <- data.frame(
  Sample = c('Zihe_1', 'Iisa_3', 'Uilk_3', 'Xojn_3', 'Sojd_3', 'Poih_4', 'Eipl_1', 'Letw_1', 'Qehq_3', 'Joxm_1'),
  `10 kbp within` = c(0.96, 0.99, 0.99, 0.98, 0.98, 0.97, 0.98, 0.98, 0.99, 0.99),
  `10-20 kbp` = c(0.96, 0.97, 0.98, 0.98, 0.98, 0.96, 0.98, 0.98, 0.98, 0.98),
  `20-30 kbp` = c(0.96, 0.97, 0.98, 0.97, 0.98, 0.95, 0.97, 0.97, 0.97, 0.98),
  `30-40 kbp` = c(0.97, 0.98, 0.98, 0.97, 0.98, 0.95, 0.97, 0.97, 0.97, 0.98),
  `40-50 kbp` = c(0.96, 0.97, 0.98, 0.97, 0.98, 0.95, 0.97, 0.97, 0.97, 0.98),
  `50-100 kbp` = c(0.95, 0.97, 0.97, 0.96, 0.97, 0.95, 0.96, 0.96, 0.97, 0.97),
  `100-200 kbp` = c(0.94, 0.96, 0.97, 0.96, 0.97, 0.94, 0.96, 0.96, 0.96, 0.97),
  `200-300 kbp` = c(0.93, 0.96, 0.97, 0.95, 0.97, 0.94, 0.95, 0.95, 0.96, 0.97),
  `300-400 kbp` = c(0.94, 0.96, 0.97, 0.95, 0.97, 0.94, 0.95, 0.95, 0.96, 0.97),
  `400-500 kbp` = c(0.94, 0.96, 0.96, 0.95, 0.97, 0.93, 0.95, 0.95, 0.95, 0.96)
)
data_melted <- melt(data, id.vars = "Sample", variable.name = "Flank_Within", value.name = "Correlation")
ggplot(data_melted, aes(x = factor(Flank_Within), y = Correlation, group = Sample, color = Sample)) +
  geom_line() +
  geom_point() +
  scale_x_discrete(labels = c("<10 kbp", "10-20 kbp", "20-30 kbp", "30-40 kbp", "40-50 kbp", "50-100 kbp", "100-200 kbp", "200-300 kbp", "300-400 kbp", "400-500 kbp")) +
  labs(x = "Distance from nearest gene on count matrix", y = "Pearson Correlation") +
  ylim(0.92, 1) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank()) +
  theme(plot.margin = margin(1, 1, 1, 2, "cm"))
```

## Visualising correlations across various lowconfidence thresholds

```{r}
library(ggplot2)

sample_data <- data.frame(
  sample = c("zihe_1", "eipl_1", "joxm_1"),
  `0.95` = c(0.93, 0.95, 0.96),
  `0.90` = c(0.79, 0.93, 0.95),
  `0.85` = c(0.90, 0.92, 0.94),
  `0.80` = c(0.88, 0.90, 0.92),
  `0.75` = c(0.85, 0.88, 0.91),
  `0.70` = c(0.83, 0.86, 0.89)
)

data_melted <- melt(sample_data, id.vars = "sample", variable.name = "Lowconf_Threshold", value.name = "Correlation")
stdev_data <- data_melted %>% group_by(sample) %>% mutate(stdev = sd(Correlation))
ggplot(data_melted, aes(x = factor(Lowconf_Threshold), y = Correlation, group = sample, color = sample)) +
  geom_line() +
  geom_point() +
  geom_errorbar(data = stdev_data, aes(ymin = Correlation - stdev, ymax = Correlation + stdev), width = 0.2) +
  scale_x_discrete(labels = c("0.95", "0.90", "0.85", "0.80", "0.75", "0.70")) +
  labs(x = "Lowconf Threshold", y = "Pearson Correlation") +
  ylim(0.75, 1) +
  theme_minimal() +
  theme(plot.margin = margin(1, 1, 1, 2, "cm"))
```

