#!/bin/bash

# ---------------------------------------------------
# The Advanced Research Computing at Hopkins (ARCH)
# User and Application Support < help@rockfish.jhu.edu >
#
# SLURM script to run the R-Studio-Server
#
# ---------------------------------------------------
#  INPUT ENVIRONMENT VARIABLES
# ---------------------------------------------------
#SBATCH --job-name=rstudio_lchanem1
#SBATCH --time=00-04:00
#SBATCH --partition=shared
#SBATCH --signal=USR2
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=lchanem1@jhu.edu
#SBATCH --output=rstudio-server.job.%j.out
# ---------------------------------------------------



module restore

# ---------------------------------------------------
#  R environment
# ---------------------------------------------------
# This session is to run this script using R loaded.

#  There are thre ways to run it:
#
#   METHOD 1: Using an R via the system module
#           No action is need, the R 4.2.1 will be loaded by RStudio-Server module


#   METHOD 2: Using an R System module.
#     Then, uncomment on this module bellow to use a R on Rockfish

#   module load seurat/4.1.1
#   module load r/3.6.3
#   module load r/4.0.2
#   module load r/4.2.0

#   METHOD 3: Using an R installed in a custom virtual environment, in this case using conda.
#
#     How to install an R version 4.2.3 using conda environment
#     $ module load anaconda && conda create -n my_env -c conda-forge r-base=4.2.3 && module unload anaconda
#     How to remove conda envs
#     $ conda remove --name my_env --all

#     Run conda_to_lua.sh script. It will customize your R conda environment into lua modulefiles.
#
#     Then, uncomment this instruction. Replace my_env to your conda env name
#
#     module load own my_env
#

# ---------------------------------------------------
# R_LIBS_USER directives for multiple environments
# ---------------------------------------------------
# Change the R_LIBS_USER path to use the libraries related with a project.

# Set R built with RStudio. Change it as you need.
export R_LIBS_USER=${HOME}/R/4.2.1

# ---------------------------------------------------
#  SHOULDN'T BE NECESSARY TO CHANGE ANYTHING BELOW THIS --
# ---------------------------------------------------

source .r-studio-variables

cat 1>&2 <<END

1. SSH tunnel from your workstation terminal (not in Rockfish), using the following command:

   ssh -N -L ${PORT}:${HOSTNAME}:${PORT} ${USER}@login.rockfish.jhu.edu

2. log in to RStudio Server in your web browser using the Rockfish cluster credentials (username and password) at:

   http://localhost:${PORT}

   user: ${USER}
   password: < Rochkfish password >

3. When done using RStudio Server, terminate the job by:

   a. Exit the RStudio Session ("power" button in the top right corner of the RStudio window)
   b. Issue the following command on the login node:

  scancel -f ${SLURM_JOB_ID}
END


rserver --server-daemonize=0 --www-enable-origin-check=1 \
        --auth-none 0 \
        --server-app-armor-enabled=0 \
        --server-user=${USER} \
        --auth-pam-helper-path "${RSTUDIO_AUTH}"

